# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oz < Formula
  desc "Config-driven CLI wizard framework"
  homepage "https://github.com/svyatov/oz"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svyatov/oz/releases/download/v0.1.0/oz_0.1.0_darwin_amd64.tar.gz"
      sha256 "aeba0d67786268e8bdc83a671df271da6401277d4fb3c6bd8648d82c9e002d97"

      define_method(:install) do
        bin.install "oz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svyatov/oz/releases/download/v0.1.0/oz_0.1.0_darwin_arm64.tar.gz"
      sha256 "e496274e74c661a7f20d55fd3420794b01c58bf73a410d31be046b1fe631c5b4"

      define_method(:install) do
        bin.install "oz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/svyatov/oz/releases/download/v0.1.0/oz_0.1.0_linux_amd64.tar.gz"
      sha256 "3335ae1f5452403e32544621062c8ed9b290a2ede48b2ba5f2a1b8313bad2428"
      define_method(:install) do
        bin.install "oz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svyatov/oz/releases/download/v0.1.0/oz_0.1.0_linux_arm64.tar.gz"
      sha256 "33b98c29a968122f9d81fb0f6e34aac1f038f50b1a117467276c525462f2813e"
      define_method(:install) do
        bin.install "oz"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/oz --version")
  end
end
