# This file was generated by GoReleaser. DO NOT EDIT.
cask "equip" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/equip"]
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "9da98b95033f867cadfe6a4205560d61e7760d61e00a5196fa030965cb16c5f6"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a5ba645ee82ed1558878f785ffb2fd19a26f17658d9ceac2ea8adbd165d295e"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2e05d83c1bc50176ba62d2beb7a720bf0c3b4a1bdc93b38f1b1de1a6a44dd6df"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec60b83fd0edaf5ab2dceb806200c496902fa046b1d4dc2ab2030bff5f16d9f1"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_linux_amd64.tar.gz"
    end
  end

  name "equip"
  desc "Terminal UI that sets which skills, plugins, and MCP servers Claude Code and Codex load"
  homepage "https://github.com/svyatov/equip"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equip"

  # No zap stanza required
end
