# This file was generated by GoReleaser. DO NOT EDIT.
cask "equip" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/equip"]
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "07644e2516bd5c0e3ef6ebb378d909efacda78cabb2c1a91e32cfe1e074dd979"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fcb6b0ac8076d05132004ad83b7d037f8bdd8764061333abe68c78d8067dd18"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ff5872b8f3924091594d6eadeaf7d10a7060dc5eca1d47b303914911309d130d"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b503cf4173b4c7a29526080e7f75c812ee69f1fe47cf059d81701965343c9833"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_linux_amd64.tar.gz"
    end
  end

  name "equip"
  desc "Terminal UI that sets which skills, plugins, and MCP servers Claude Code and Codex load"
  homepage "https://github.com/svyatov/equip"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equip"

  # No zap stanza required
end
