# This file was generated by GoReleaser. DO NOT EDIT.
cask "equip" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/equip"]
    end
  end

  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "78b0b6af1b292d07240f632055b91c8c6e14ce13d1c3dc0163d9de580844e77c"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b0e50885b9be7779bc179a8901d8a1bd320acddd96c353e20fc3b38fad74277"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a2d2b599dad1004691d596013d10690a683a33ca8daa118cda86077ffd4ea827"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a47f5f11e227c7735ce69cfda4b7b51ed6884aac1fc3f568642f33a24cbebc7"
      url "https://github.com/svyatov/equip/releases/download/v#{version}/equip_#{version}_linux_amd64.tar.gz"
    end
  end

  name "equip"
  desc "Terminal UI that sets which skills, plugins, and MCP servers Claude Code and Codex load"
  homepage "https://github.com/svyatov/equip"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equip"

  # No zap stanza required
end
