# This file was generated by GoReleaser. DO NOT EDIT.
cask "handrail" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "14a0c36bcef1a693d9ef61fb0c0426c3b6299122f69b4d691d268a7090401936"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "51973996fdb744fc92027fd40cf0e4bd59981155f5052a0d354f5df3da59bbb2"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "adeaa00ae7b8f033b784bfb004e0943f03eb106cc0253bfe7bbc17c1b4dad145"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "072c46de1d89a8cd9e1bf6da14a33afb73a5314cc2d6f20d178b2f5ead6bf927"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_linux_amd64.tar.gz"
    end
  end

  name "handrail"
  desc "Cross-harness guardrail manager for agentic coding harnesses"
  homepage "https://github.com/svyatov/handrail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handrail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handrail"]
    end
  end

  # No zap stanza required
end
