# This file was generated by GoReleaser. DO NOT EDIT.
cask "handrail" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/handrail"]
    end
  end

  version "0.4.2"

  on_macos do
    on_arm do
      sha256 "c8835eaa01e351ccd7f0da127f0b60dc4c1292acc058f5313604afdb5d53c97a"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "870488b0fa9973ae68ffd4e2ba32627ff07afadd383f88cef4988475427d7d80"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ce94d3dbf0dfb7078087dca1915c4466a6d9169676bf705dbd9845da2cdd9ab"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8664a336b836c87e7a9ff020f71762bf8169422e0299916df78f43bbb6f98b2"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_linux_amd64.tar.gz"
    end
  end

  name "handrail"
  desc "Cross-harness guardrail manager for agentic coding harnesses"
  homepage "https://github.com/svyatov/handrail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handrail"

  # No zap stanza required
end
