# This file was generated by GoReleaser. DO NOT EDIT.
cask "handrail" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "b8b32bfdf3a0665e90961e461c5519ec3cb9e936e092211f6ac9caa5158e58d3"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a52ea00a1bbad09b7c4a3e92f94576b7015b412138c6fc152c25fe8cd274de08"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26eaeb27f2eba768fbcf69c805f3d189acf0face9bd132c921da70bab459a48e"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfcaf26cdcc4174f4d8dce8c76cd205a0163ab4e522658c55d3359609b76def1"
      url "https://github.com/svyatov/handrail/releases/download/v#{version}/handrail_#{version}_linux_arm64.tar.gz"
    end
  end

  name "handrail"
  desc "Cross-harness guardrail manager for agentic coding harnesses"
  homepage "https://github.com/svyatov/handrail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handrail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handrail"]
    end
  end

  # No zap stanza required

end
