# This file was generated by GoReleaser. DO NOT EDIT.
cask "oz" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "beff793a4b3d8f1c1d572f3a634dbedf0ae99802069fb4d310f944515a0e8428"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0222ed28dba34d6c8b77e0e6d5f7a324da2c4c89ac02d12fc9cb54ca6a136f79"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8d23f1d94b609d08ca772d198181d821a9d2ace62818e50c0696241a4beca140"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a781c250e0e6880004e18ca5c2d768ac28a5c9fa785bdf4972151676ee3e6f19"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oz"
  desc "Config-driven CLI wizard framework"
  homepage "https://github.com/svyatov/oz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oz"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/oz"]
    end
  end
  generate_completions_from_executable "oz",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
