# This file was generated by GoReleaser. DO NOT EDIT.
cask "oz" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "fee54f781a5f794f80ba171882963b5c7e319642dda553779539f2a45b5f67b9"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cbd88a52c548b1cbe4b59771e58097c635fcdb37cc7d898dde0d35db469a76f1"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c54d606b083365d1f15fa1e003146caef5c7f71acdb8ea2dc05721fb9f473b8"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "09776f41c8325087e29ce432ba6c1705174b1dfc2fc059005b44d21cb1a1bb9d"
      url "https://github.com/svyatov/oz/releases/download/v#{version}/oz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oz"
  desc "Config-driven CLI wizard framework"
  homepage "https://github.com/svyatov/oz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oz"]
    end
  end
  generate_completions_from_executable "oz",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
